spring.application.name=hype-link-platfrom

# Server port
server.port = 8080

# H2 database config
spring.datasource.url=jdbc:h2:mem:hypelinkldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=hl
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Base URL for generated short links
app.base-url=http://localhost:8080